### ISSUE TITLE
Typo singed/signed in README

### ISSUE THREAD

**Issue by eribertomota** [sshock/AFFLIBv3#1]
From https://github.com/simsong/AFFLIBv3/issues/18

--- AFF allows files to be digital singed, to provide for
--- AFF allows files to be digital signed, to provide for

https://github.com/sshock/AFFLIBv3/blob/master/README

Regards,

Eriberto

**Comment by sshock** [comment]
Fixed in 60c6520237f78158dfd48197ab0d869e26da4e18

**Comment by eribertomota** [comment]
Thanks!

2015-08-23 22:43 GMT-03:00 Phillip Hellewell <notifications@github.com>:

**Comment by hartwork** [comment]
Excellent!
