### ISSUE TITLE
Fail to build woth OpenSSL 1.1.0

### ISSUE THREAD

**Issue by eribertomota** [sshock/AFFLIBv3#10]
Hi,

Debian will use OpenSSL as default soon. This bug[1] says about issues between AFFLib and OpenSSL 1.1.0. Can you take a look?

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828228

Thanks a lot in advance.

Regards,

Eriberto

**Comment by sshock** [comment]
Sure; I don't think this will be very hard to fix.

**Comment by sshock** [comment]
Fixed in ab1306d320dd482c277ac7fe3469440acd963162.

**Comment by eribertomota** [comment]
Thanks!

2016-08-24 1:40 GMT-03:00 Phillip Hellewell <notifications@github.com>:

**Comment by sshock** [comment]
(Re-opened because not totally fixed yet.  More files needed to be updated, not just crypto.cpp.)

**Comment by sshock** [comment]
Fix take 2 in 507811efaddf7b66b7cec183a8aeb38e442b47f0.

**Comment by eribertomota** [comment]
Thanks! Building fine in Debian. I will open a new bug about warning
messages when building.

Regards,

Eriberto


2016-09-12 15:13 GMT-03:00 Phillip Hellewell <notifications@github.com>:
