### ISSUE TITLE
Warnings when building

### ISSUE THREAD

**Issue by eribertomota** [sshock/AFFLIBv3#11]
Hi,

The version 3.7.10 produces some warnings when building. The attached log, from Debian building system, shows all warnings. 

Thanks in advance.

Regards,

Eriberto

[build.log.txt](https://github.com/sshock/AFFLIBv3/files/468581/build.log.txt)

**Comment by sshock** [comment]
Fixed in bdc6228a580d28ac5a57fead2e7e5182367cd98c.
