### ISSUE TITLE
Spelling error in binary

### ISSUE THREAD

**Issue by eribertomota** [sshock/AFFLIBv3#12]
Hi,

Debian building system says via lintian:

I: afflib-tools: spelling-error-in-binary usr/bin/affcopy Deleteing Deleting
I: afflib-tools: spelling-error-in-binary usr/bin/affsign Deleteing Deleting

The attached patch fixes the issue. Thanks!

Regards,

Eriberto

[afflib.patch.txt](https://github.com/sshock/AFFLIBv3/files/468591/afflib.patch.txt)

**Comment by sshock** [comment]
Fixed in 62caa281494602a43b2774f33affd323811e435f
