### ISSUE TITLE
Convert stream data to aff

### ISSUE THREAD

**Issue by zhouwanchun1993** [sshock/AFFLIBv3#25]
How can I convert a stream data to an aff file. Is there a function (such as update as below) can be invoked once or multiple times to write spacifiec data to aff file?

For example:
// do something to initialize aff context or do somethings else
char buffer[100] = “Today is a nice day”;
update(buffer,strlen(buffer));  // update can be invoked once or multiple times.
// close file or do something else

**Comment by sshock** [comment]
Yes, after calling af_open() to create the aff and get an AFFLIB*, and then call af_enable_compression() if you want compression, then you can call af_write() one or more times to write any data you want, e.g.,

af_write(aff, buffer, strlen(buffer));

**Comment by zhouwanchun1993** [comment]
Ok. It works. Thank you. and I find total size to be written must be the times of 512 bytes,otherwise the output aff file can't be opened correctly with FTK Imager.

**Comment by sshock** [comment]
Glad to hear it all worked out for you.
