### ISSUE TITLE
packaged binaries?

### ISSUE THREAD

**Issue by DexterHaslem** [sshock/AFFLIBv3#26]
the doc file at https://github.com/sshock/AFFLIBv3/blob/master/README_Win32.txt  mentions there is a zip of precompiled binaries. I looked around releases a bit and only could find source code. is this readme simply out of date?

**Comment by sshock** [comment]
Yes, the readme was out-of-date.  I went ahead and updated it in e32b671f7dc78d6d2fc29018eb37406619849313.  Please take a look.
