### ISSUE TITLE
Unable to configure due to input file missing

### ISSUE THREAD

**Issue by samrajcse** [sshock/AFFLIBv3#27]
Hi Team,

I can able to complete the ./configure command due to following error.

**Stacktrace:**
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `lib/Makefile.in'

**Comment by sshock** [comment]
Did you run ./bootstrap.sh first?

**Comment by samrajcse** [comment]
Yeah. I did that.

**Comment by sshock** [comment]
I can't reproduce your problem.  Do you have a lib/Makefile.in or not?  When you run bootstrap.sh it should create that.

Did you get an error when running bootstrap.sh?

**Comment by sshock** [comment]
No response in 20 days so closing...
