### ISSUE TITLE
Win32 Upload Lib

### ISSUE THREAD

**Issue by mloom00** [sshock/AFFLIBv3#33]
@sshock I cannot get the build of this to work on Windows. I came across many similar issues discussed in the readme, but it has been one issue after another. If possible can you get an uploaded static library so that my project can make use of it? 

In reference to the Windows getopt issue. I pulled the .c/.h files for these from the [IoTivity](https://github.com/iotivity/iotivity/tree/master/resource/c_common/windows) project to make it work. Seemed like a reliable source.

**Comment by sshock** [comment]
The library itself should build no problem, but the tools are harder; I've personally never gotten the tools to build on windows.

Please read through all the comments in #24.
