### ISSUE TITLE
afflib-3.7.17 (with commit 1af39770803caa768b5991f010a298918c19df7a) tests fail

### ISSUE THREAD

**Issue by pacho2** [sshock/AFFLIBv3#38]
After applying:
https://github.com/sshock/AFFLIBv3/commit/1af39770803caa768b5991f010a298918c19df7a.patch

I hit now two new test failures:
PASS: aftest
============================================================================
Testsuite summary for AFFLIB 3.7.17
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Leaving directory '/var/tmp/portage/app-forensics/afflib-3.7.17/work/AFFLIBv3-3.7.17/lib'
make[2]: Leaving directory '/var/tmp/portage/app-forensics/afflib-3.7.17/work/AFFLIBv3-3.7.17/lib'
make[1]: Leaving directory '/var/tmp/portage/app-forensics/afflib-3.7.17/work/AFFLIBv3-3.7.17/lib'
Making check in tools
make[1]: Entering directory '/var/tmp/portage/app-forensics/afflib-3.7.17/work/AFFLIBv3-3.7.17/tools'
make  check-TESTS
make[2]: Entering directory '/var/tmp/portage/app-forensics/afflib-3.7.17/work/AFFLIBv3-3.7.17/tools'
make[3]: Entering directory '/var/tmp/portage/app-forensics/afflib-3.7.17/work/AFFLIBv3-3.7.17/tools'
PASS: test_afsegment.sh
PASS: test_crypto.sh
FAIL: test_recovery.sh
FAIL: test_signing.sh
PASS: test_passphrase.sh
============================================================================
Testsuite summary for AFFLIB 3.7.17
============================================================================
# TOTAL: 5
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See tools/test-suite.log
Please report to https://github.com/sshock/AFFLIBv3
============================================================================
make[3]: *** [Makefile:952: test-suite.log] Error 1
make[3]: Leaving directory '/var/tmp/portage/app-forensics/afflib-3.7.17/work/AFFLIBv3-3.7.17/tools'
make[2]: *** [Makefile:1060: check-TESTS] Error 2
make[2]: Leaving directory '/var/tmp/portage/app-forensics/afflib-3.7.17/work/AFFLIBv3-3.7.17/tools'
make[1]: *** [Makefile:1161: check-am] Error 2
make[1]: Leaving directory '/var/tmp/portage/app-forensics/afflib-3.7.17/work/AFFLIBv3-3.7.17/tools'
make: *** [Makefile:566: check-recursive] Error 1
[test-suite.log](https://github.com/sshock/AFFLIBv3/files/2871741/test-suite.log)

**Comment by sshock** [comment]
Hi @pacho2 

I'm seeing these two failures with or without 1af39770803caa768b5991f010a298918c19df7a, so I don't think it's related.  I think these were already broken.

**Comment by sshock** [comment]
the `test_recovery.sh` and `test_signing.sh` fail for me even checking out older revisions back to 7 years ago...

**Comment by sshock** [comment]
found the problem: it was freeing the evp md context before it was done using it

surprised this bug went unnoticed for so long, but it could be that it hasn't been that long because maybe OpenSSL changed how EVP_MD_CTX_free works; e.g., perhaps it zeroes out the data now and didn't used to

**Comment by sshock** [comment]
looks like it was actually me who introduced the issue in Aug 2016 when adding support for OpenSSL 1.1.0 in ab1306d320dd482c277ac7fe3469440acd963162

not sure why when I tested with really old revisions it was also failing; I must have been doing something wrong

**Comment by pacho2** [comment]
All tests pass with 3.7.18 :D

I guess that  I didn't notice them failing because of the previous test that was failing before and, then, I wasn't running the rest of the testsuite

Thanks a lot
