### ISSUE TITLE
afflib.cpp:820: use of out of scope variable

### ISSUE THREAD

**Issue by dcb314** [sshock/AFFLIBv3#39]
afflib.spec.out:[afflib.cpp:820] -> [afflib.cpp:816] -> [afflib.cpp:836]: (error) Using pointer to local variable 'aesname' that is out of scope.

**Comment by sshock** [comment]
cool, can you submit a pull request?

**Comment by dcb314** [comment]
Sorry, no.

I've found another one.

qemu/block-raw-posix.c:657] -> [qemu/block-raw-posix.c:642] -> [qemu/block-raw-posix.c:691]: (error) Using pointer to local variable 'bsdPath' that is out of scope.

**Comment by sshock** [comment]
ok, well it's easy enough, so I'll just fix it
