### ISSUE TITLE
lzma443/C/Common/String.h:434: bad array size ?

### ISSUE THREAD

**Issue by dcb314** [sshock/AFFLIBv3#45]
../lzma443/C/Common/String.h:434:58: warning: division 'sizeof (const char*) / sizeof (const char)' does not compute the number of array elements [-Wsizeof-pointer-div]

Wsizeof-pointer-div is a new warning in gcc.

**Comment by sshock** [comment]
I don't think this part of this old lzma code is even being used, but I'll fix it real quick...

**Comment by sshock** [comment]
fixed in f103f66c4924b8678a3f72fbe5fa68e7fc3f7bc0
