### ISSUE TITLE
Query, not an issue

### ISSUE THREAD

**Issue by ChangoMunk** [sshock/AFFLIBv3#52]
Hi, 

is this able to work with aff4-L? I'm looking for a way to convert the logical contents of an aff4-L into a zip file and was wondering if this would facilitate?

Thanks in advance!

**Comment by sshock** [comment]
Sorry, no.  AFF4 (and AFF4-L) is totally different than AFF3.

Perhaps one of these links will help you:
* http://www2.aff4.org/
* https://github.com/aff4/pyaff4

**Comment by ChangoMunk** [comment]
Thanks a lot for replying. Much appreciated.
