### ISSUE TITLE
'affcat -b' does not work

### ISSUE THREAD

**Issue by chrfranke** [sshock/AFFLIBv3#56]
```
$ affcat -b file.aff
affcat: unknown option -- b
affcat version 3.7.20
...
    -b      --- Output BADFALG for bad blocks (default is NULLs)
...

```

The reason is quite obvious: `'b'` is missing in the `getopt()` string:
```cpp
    while ((ch = getopt(argc, argv, "s:S:p:lLh?dqnvr:")) != -1) {
      ...
	case 'b':
	    opt_badflag = 1;
	    break;
      ...
    }
```
Apparently never tested since the early days :-)

**Comment by sshock** [comment]
> Apparently never tested since the early days :-)

Yeah, very interesting.  Alright, well I'll go ahead and allow it to work.
