### ISSUE TITLE
man affcat: Suggest to clarify that '-q' is the default

### ISSUE THREAD

**Issue by chrfranke** [sshock/AFFLIBv3#57]
```
$ man affcat
       ...
       Missing pages will not be padded, but the fact that they are missing will be noted on STDERR.
       ...
```
Users might assume that there are no missing pages if nothing is output to stderr. This is not the case unless `-n` is specified because `-q` is the default.

**Comment by sshock** [comment]
Good catch.  I'll update this to be more clear.
