### ISSUE TITLE
3.7.7 ncurses and Linux

### ISSUE THREAD

**Issue by conraid** [sshock/AFFLIBv3#6]
In Slackware Linux 14.2rc1 build fails with

`
libtool: link: g++ -g -O2 -D_FORTIFY_SOURCE=2 -Wall -g -o .libs/affix affix.o  -L/usr/local/lib ../lib/.libs/libafflib.so /usr/lib64/../lib64/libstdc++.so -lm -lcrypto /usr/lib64/libexpat.so -ltermcap -lrt -lz -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/lib64/../lib64
affinfo.o: In function 'bold(int)':
/tmp/AFFLIBv3-3.7.7-orig/tools/affinfo.cpp:95: undefined reference to 'cur_term'
collect2: error: ld returned 1 exit status
Makefile:751: set di istruzioni per l'obiettivo "affinfo" non riuscito
make[2]: *** [affinfo] Errore 1
make[2]: *** Attesa per i processi non terminati....
mv -f .deps/affdiskprint.Tpo .deps/affdiskprint.Po
make[2]: uscita dalla directory "/tmp/AFFLIBv3-3.7.7/tools"
Makefile:567: set di istruzioni per l'obiettivo "all-recursive" non riuscito
make[1]: *** [all-recursive] Errore 1
make[1]: uscita dalla directory "/tmp/AFFLIBv3-3.7.7"
Makefile:432: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2`
[configure.ac.txt](https://github.com/sshock/AFFLIBv3/files/190436/configure.ac.txt)

Reverted ncurses patch in configure work fine

`
--- AFFLIBv3-3.7.7/configure.ac 2015-10-02 00:55:01.000000000 +0200
+++ AFFLIBv3-3.7.5/configure.ac 2014-10-11 08:19:44.000000000 +0200
@@ -81,7 +81,7 @@ AC_STRUCT_ST_RDEV
 
 
 # Specific headers that I plan to use
-AC_CHECK_HEADERS([arpa/inet.h assert.h ctype.h dmalloc.h err.h errno.h fcntl.h getopt.h inttypes.h linux/fs.h malloc.h netinet/in.h regex.h signal.h stdint.h stdio.h stdlib.h string.h sys/cdefs.h sys/disk.h sys/file.h sys/ioctl.h sys/ioctl.h sys/param.h sys/param.h sys/socket.h sys/signal.h sys/stat.h sys/time.h sys/types.h sys/vfs.h sysexits.h term.h time.h unistd.h zlib.h _mingw.h])
+AC_CHECK_HEADERS([arpa/inet.h assert.h ctype.h dmalloc.h err.h errno.h fcntl.h getopt.h inttypes.h linux/fs.h malloc.h ncurses/term.h netinet/in.h regex.h signal.h stdint.h stdio.h stdlib.h string.h sys/cdefs.h sys/disk.h sys/file.h sys/ioctl.h sys/ioctl.h sys/param.h sys/param.h sys/socket.h sys/signal.h sys/stat.h sys/time.h sys/types.h sys/vfs.h sysexits.h term.h time.h unistd.h zlib.h _mingw.h])
 
 AC_CHECK_LIB([regex],[regcomp])        # see if we need -lregex
 
@@ -115,9 +115,10 @@ AC_LANG_POP([C++])
 AC_CHECK_HEADERS([readline/readline.h])
 AC_CHECK_HEADERS([curses.h termcap.h])
 AC_CHECK_LIB([readline],[readline],, AC_MSG_RESULT([readline not installed]))
+AC_CHECK_LIB([ncurses],[initscr],, AC_MSG_RESULT([ncurses not installed]))
 AC_CHECK_LIB([z],[uncompress],, AC_MSG_ERROR([zlib not installed; cannot continue. Try adding zlib-dev or zlib1g-dev.]))
 AC_CHECK_LIB([rt],[aio_error64])
-AC_SEARCH_LIBS(tgetent, termlib termcap curses)
+AC_SEARCH_LIBS(tgetent, termlib termcap tinfo curses ncurses)
 AC_CHECK_FUNCS(putp tputs tgoto tgetstr tgetnum gotorc beep endwin setupterm printw)
 
 ################################################################
`

**Comment by sshock** [comment]
Hi conraid, thanks!  Can you submit it as a pull request?

**Comment by sshock** [comment]
Actually I think I might just rip out the curses support.  It's only really used in one place in affinfo and it doesn't even work there.

**Comment by conraid** [comment]
Done.

I don't know for ncurses, I use it only to build sleuthkit and bulk_extractor.

**Comment by sshock** [comment]
Fixed in 61bf90d3c0211be89c39ee539b74680a070258b1.
